<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260918153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adiciona imagens aos eventos.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration requires PostgreSQL.'
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE event_images (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                event_id INT NOT NULL,
                storage_name VARCHAR(255) NOT NULL,
                original_name VARCHAR(255) NOT NULL,
                mime_type VARCHAR(100) NOT NULL,
                size INT NOT NULL,
                position INT NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        $this->addSql(
            'CREATE INDEX idx_event_images_event_position
             ON event_images (event_id, position, id)'
        );

        $this->addSql(
            'CREATE UNIQUE INDEX uniq_event_images_event_position
             ON event_images (event_id, position)'
        );

        $this->addSql(
            'ALTER TABLE event_images
             ADD CONSTRAINT fk_event_images_event
             FOREIGN KEY (event_id)
             REFERENCES events (id)
             ON DELETE CASCADE'
        );

        $this->addSql(
            'ALTER TABLE event_images
             ADD CONSTRAINT chk_event_images_size
             CHECK (size > 0)'
        );

        $this->addSql(
            'ALTER TABLE event_images
             ADD CONSTRAINT chk_event_images_position
             CHECK (position >= 0)'
        );
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration requires PostgreSQL.'
        );

        $this->addSql('DROP TABLE event_images');
    }
}