<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260910170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial church domain: users, ministries, memberships, posts, comments, events and schedules.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql('CREATE TABLE ministry_schedules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, visibility VARCHAR(20) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_by INT NOT NULL, ministry_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_schedules_upcoming ON ministry_schedules (status, starts_at, id)');
        $this->addSql('CREATE INDEX idx_schedules_ministry_upcoming ON ministry_schedules (ministry_id, status, starts_at, id)');
        $this->addSql('CREATE INDEX idx_schedules_creator ON ministry_schedules (created_by)');
        $this->addSql('CREATE INDEX IDX_72D7D4F1C7266135 ON ministry_schedules (ministry_id)');
        $this->addSql('CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, location VARCHAR(180) DEFAULT NULL, address VARCHAR(500) DEFAULT NULL, starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, visibility VARCHAR(20) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_by INT NOT NULL, ministry_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_events_upcoming ON events (status, starts_at, id)');
        $this->addSql('CREATE INDEX idx_events_ministry_upcoming ON events (ministry_id, status, starts_at, id)');
        $this->addSql('CREATE INDEX idx_events_creator ON events (created_by)');
        $this->addSql('CREATE INDEX IDX_5387574AC7266135 ON events (ministry_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL, email_normalized VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, phone VARCHAR(30) DEFAULT NULL, birth_date DATE DEFAULT NULL, role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_users_status_created_id ON users (status, created_at, id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email_normalized ON users (email_normalized)');
        $this->addSql('CREATE TABLE user_ministries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_leader BOOLEAN NOT NULL, status VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, left_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, ministry_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_user_ministries_user_status_ministry ON user_ministries (user_id, status, ministry_id)');
        $this->addSql('CREATE INDEX idx_user_ministries_ministry_status_leader_user ON user_ministries (ministry_id, status, is_leader, user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_ministries_pair ON user_ministries (user_id, ministry_id)');
        $this->addSql('CREATE INDEX IDX_9D29B3A6A76ED395 ON user_ministries (user_id)');
        $this->addSql('CREATE INDEX IDX_9D29B3A6C7266135 ON user_ministries (ministry_id)');
        $this->addSql('CREATE TABLE ministries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(160) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ministries_slug ON ministries (slug)');
        $this->addSql('CREATE TABLE posts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, content TEXT NOT NULL, visibility VARCHAR(20) NOT NULL, comments_enabled BOOLEAN NOT NULL, status VARCHAR(16) NOT NULL, published_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, author_id INT NOT NULL, ministry_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_posts_feed ON posts (status, published_at, id)');
        $this->addSql('CREATE INDEX idx_posts_ministry_feed ON posts (ministry_id, status, published_at, id)');
        $this->addSql('CREATE INDEX idx_posts_author ON posts (author_id)');
        $this->addSql('CREATE INDEX IDX_885DBAFAC7266135 ON posts (ministry_id)');
        $this->addSql('CREATE TABLE comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, post_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_comments_post ON comments (post_id, status, created_at, id)');
        $this->addSql('CREATE INDEX idx_comments_user ON comments (user_id)');
        $this->addSql('CREATE INDEX IDX_5F9E962A4B89032C ON comments (post_id)');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT FK_72D7D4F1DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT FK_72D7D4F1C7266135 FOREIGN KEY (ministry_id) REFERENCES ministries (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574ADE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574AC7266135 FOREIGN KEY (ministry_id) REFERENCES ministries (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_ministries ADD CONSTRAINT FK_9D29B3A6A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_ministries ADD CONSTRAINT FK_9D29B3A6C7266135 FOREIGN KEY (ministry_id) REFERENCES ministries (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAC7266135 FOREIGN KEY (ministry_id) REFERENCES ministries (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A4B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN (\'ADMIN\', \'PASTOR\', \'LEADER\', \'MEMBER\'))');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT chk_users_status CHECK (status IN (\'ACTIVE\', \'INACTIVE\', \'BLOCKED\'))');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT chk_users_name CHECK (char_length(btrim(name)) > 0)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT chk_users_email_normalized CHECK (email_normalized = lower(btrim(email)))');
        $this->addSql('ALTER TABLE ministries ADD CONSTRAINT chk_ministries_status CHECK (status IN (\'ACTIVE\', \'INACTIVE\'))');
        $this->addSql('ALTER TABLE ministries ADD CONSTRAINT chk_ministries_name CHECK (char_length(btrim(name)) > 0)');
        $this->addSql('ALTER TABLE ministries ADD CONSTRAINT chk_ministries_slug CHECK (slug ~ \'^[a-z0-9]+(-[a-z0-9]+)*$\')');
        $this->addSql('ALTER TABLE ministries ADD CONSTRAINT chk_ministries_description CHECK (description IS NULL OR char_length(description) <= 10000)');
        $this->addSql('ALTER TABLE user_ministries ADD CONSTRAINT chk_user_ministries_status CHECK (status IN (\'ACTIVE\', \'INACTIVE\'))');
        $this->addSql('ALTER TABLE user_ministries ADD CONSTRAINT chk_user_ministries_leader_active CHECK (NOT is_leader OR status = \'ACTIVE\')');
        $this->addSql('ALTER TABLE user_ministries ADD CONSTRAINT chk_user_ministries_dates CHECK (left_at IS NULL OR left_at >= joined_at)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT chk_posts_status CHECK (status IN (\'DRAFT\', \'PUBLISHED\', \'ARCHIVED\'))');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT chk_posts_visibility CHECK (visibility IN (\'PUBLIC\', \'MINISTRY_MEMBERS\'))');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT chk_posts_private_ministry CHECK (visibility <> \'MINISTRY_MEMBERS\' OR ministry_id IS NOT NULL)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT chk_posts_published_at CHECK (status <> \'PUBLISHED\' OR published_at IS NOT NULL)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT chk_posts_title CHECK (char_length(btrim(title)) > 0)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT chk_posts_content CHECK (char_length(btrim(content)) > 0 AND char_length(content) <= 50000)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT chk_comments_status CHECK (status IN (\'VISIBLE\', \'HIDDEN\', \'DELETED\'))');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT chk_comments_content CHECK (char_length(btrim(content)) > 0 AND char_length(content) <= 5000)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT chk_events_status CHECK (status IN (\'DRAFT\', \'PUBLISHED\', \'CANCELLED\', \'ARCHIVED\'))');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT chk_events_visibility CHECK (visibility IN (\'PUBLIC\', \'MINISTRY_MEMBERS\'))');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT chk_events_private_ministry CHECK (visibility <> \'MINISTRY_MEMBERS\' OR ministry_id IS NOT NULL)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT chk_events_dates CHECK (ends_at IS NULL OR ends_at >= starts_at)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT chk_events_title CHECK (char_length(btrim(title)) > 0)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT chk_events_description CHECK (description IS NULL OR char_length(description) <= 50000)');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT chk_ministry_schedules_status CHECK (status IN (\'DRAFT\', \'PUBLISHED\', \'CANCELLED\', \'ARCHIVED\'))');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT chk_ministry_schedules_visibility CHECK (visibility IN (\'PUBLIC\', \'MINISTRY_MEMBERS\'))');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT chk_ministry_schedules_private_ministry CHECK (visibility <> \'MINISTRY_MEMBERS\' OR ministry_id IS NOT NULL)');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT chk_ministry_schedules_dates CHECK (ends_at IS NULL OR ends_at >= starts_at)');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT chk_ministry_schedules_title CHECK (char_length(btrim(title)) > 0)');
        $this->addSql('ALTER TABLE ministry_schedules ADD CONSTRAINT chk_ministry_schedules_description CHECK (description IS NULL OR char_length(description) <= 50000)');

    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql('DROP TABLE comments');
        $this->addSql('DROP TABLE posts');
        $this->addSql('DROP TABLE ministry_schedules');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE user_ministries');
        $this->addSql('DROP TABLE ministries');
        $this->addSql('DROP TABLE users');
    }
}
