<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260922120000 extends AbstractMigration
{
    public function getDescription(): string { return 'Adiciona caixa de notificacoes, preferencias, dispositivos e fila push.'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql("CREATE TABLE notification_preferences (user_id INT NOT NULL, push_enabled BOOLEAN NOT NULL DEFAULT TRUE, church_push_enabled BOOLEAN NOT NULL DEFAULT TRUE, ministry_push_enabled BOOLEAN NOT NULL DEFAULT TRUE, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(user_id))");
        $this->addSql("CREATE TABLE push_devices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, session_id VARCHAR(32) NOT NULL, expo_push_token VARCHAR(255) NOT NULL, platform VARCHAR(10) NOT NULL, status VARCHAR(10) NOT NULL, last_seen_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by_id INT NOT NULL, scope VARCHAR(20) NOT NULL, ministry_id INT DEFAULT NULL, target_user_id INT DEFAULT NULL, title VARCHAR(120) NOT NULL, body TEXT NOT NULL, route VARCHAR(255) DEFAULT NULL, idempotency_key VARCHAR(64) NOT NULL, payload_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE notification_recipients (notification_id INT NOT NULL, user_id INT NOT NULL, read_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(notification_id, user_id))");
        $this->addSql("CREATE TABLE push_deliveries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notification_id INT NOT NULL, device_id INT NOT NULL, status VARCHAR(12) NOT NULL, attempts SMALLINT NOT NULL DEFAULT 0, next_attempt_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ticket_id VARCHAR(255) DEFAULT NULL, last_error_code VARCHAR(80) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_push_device_token ON push_devices (expo_push_token)');
        $this->addSql('CREATE INDEX idx_push_device_session ON push_devices (session_id, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_notification_idempotency ON notifications (created_by_id, idempotency_key)');
        $this->addSql('CREATE INDEX idx_notification_recipient_user ON notification_recipients (user_id, notification_id DESC)');
        $this->addSql('CREATE UNIQUE INDEX uniq_push_delivery ON push_deliveries (notification_id, device_id)');
        $this->addSql('CREATE INDEX idx_push_delivery_queue ON push_deliveries (next_attempt_at, id)');
        $this->addSql("ALTER TABLE notification_preferences ADD CONSTRAINT fk_notification_preferences_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE, ADD CONSTRAINT chk_notification_preferences CHECK (push_enabled IN (TRUE,FALSE))");
        $this->addSql("ALTER TABLE push_devices ADD CONSTRAINT fk_push_device_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE, ADD CONSTRAINT fk_push_device_session FOREIGN KEY (session_id) REFERENCES auth_sessions (id) ON DELETE CASCADE, ADD CONSTRAINT chk_push_device_platform CHECK (platform IN ('ANDROID','IOS')), ADD CONSTRAINT chk_push_device_status CHECK (status IN ('ACTIVE','INVALID'))");
        $this->addSql("ALTER TABLE notifications ADD CONSTRAINT fk_notification_creator FOREIGN KEY (created_by_id) REFERENCES users (id), ADD CONSTRAINT fk_notification_ministry FOREIGN KEY (ministry_id) REFERENCES ministries (id), ADD CONSTRAINT fk_notification_target FOREIGN KEY (target_user_id) REFERENCES users (id), ADD CONSTRAINT chk_notification_scope CHECK ((scope = 'CHURCH' AND ministry_id IS NULL AND target_user_id IS NULL) OR (scope = 'MINISTRY' AND ministry_id IS NOT NULL AND target_user_id IS NULL) OR (scope = 'USER' AND ministry_id IS NULL AND target_user_id IS NOT NULL))");
        $this->addSql('ALTER TABLE notification_recipients ADD CONSTRAINT fk_notification_recipient_notification FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE, ADD CONSTRAINT fk_notification_recipient_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql("ALTER TABLE push_deliveries ADD CONSTRAINT fk_push_delivery_notification FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE, ADD CONSTRAINT fk_push_delivery_device FOREIGN KEY (device_id) REFERENCES push_devices (id) ON DELETE CASCADE, ADD CONSTRAINT chk_push_delivery_status CHECK (status IN ('PENDING','RETRY','SENT','FAILED'))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE push_deliveries');
        $this->addSql('DROP TABLE notification_recipients');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE push_devices');
        $this->addSql('DROP TABLE notification_preferences');
    }
}
