<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adiciona imagens às publicações.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration requires PostgreSQL.'
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE post_images (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                post_id INT NOT NULL,
                storage_name VARCHAR(255) NOT NULL,
                original_name VARCHAR(255) NOT NULL,
                mime_type VARCHAR(100) NOT NULL,
                size INT NOT NULL,
                position INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        $this->addSql(
            'CREATE INDEX idx_post_images_post_position ON post_images (post_id, position, id)'
        );

        $this->addSql(
            'ALTER TABLE post_images ADD CONSTRAINT fk_post_images_post
            FOREIGN KEY (post_id)
            REFERENCES posts (id)
            ON DELETE CASCADE'
        );

        $this->addSql(
            'ALTER TABLE post_images ADD CONSTRAINT chk_post_images_size
            CHECK (size > 0)'
        );

        $this->addSql(
            'ALTER TABLE post_images ADD CONSTRAINT chk_post_images_position
            CHECK (position >= 0)'
        );
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration requires PostgreSQL.'
        );

        $this->addSql('DROP TABLE post_images');
    }
}