<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260911050000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Transactional audit records for critical user access changes, with bounded metadata and preserved actor references.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql(<<<'SQL'
            CREATE TABLE audit_logs (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                actor_id INT DEFAULT NULL,
                action VARCHAR(80) NOT NULL,
                entity_type VARCHAR(40) NOT NULL,
                entity_id INT NOT NULL,
                metadata JSONB NOT NULL,
                request_id VARCHAR(32) DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_audit_logs_entity_created ON audit_logs (entity_type, entity_id, created_at, id)');
        $this->addSql('CREATE INDEX idx_audit_logs_actor_created ON audit_logs (actor_id, created_at, id)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_action CHECK (action ~ '^[a-z][a-z0-9_.]*$')");
        $this->addSql("ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_entity CHECK (entity_type ~ '^[a-z][a-z0-9_]*$' AND entity_id > 0)");
        $this->addSql("ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_metadata CHECK (jsonb_typeof(metadata) = 'object' AND octet_length(metadata::text) <= 4096)");
        $this->addSql("ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_request CHECK (request_id IS NULL OR request_id ~ '^[a-f0-9]{32}$')");
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql('DROP TABLE audit_logs');
    }
}
